// Article routes.
//
// GET /articles            → list of articles, newest first (no text)
// GET /articles/:id        → one article with its text
// GET /articles/:id/audio  → the MP3 reading of the article
//
// Read-only: articles are written by the ingestion job, never through the API.
// No assertParticipant here: articles are the same for every signed-in user. Guests
// have no JWT and therefore no access, like for the quiz statistics.

import { Router, Request, Response } from 'express';
import { authMiddleware } from '../middleware/auth';
import { getArticle, getArticleAudio, listArticles } from '../services/articleService';
import { ARTICLE_LEVELS, ArticleLevel } from '../services/articleParser';
import { handleError } from '../utils/errors';

const router = Router();

router.use(authMiddleware);

// Article ids are UUIDs generated by Prisma. Checking the shape here answers 400 to
// garbage without a database query.
const UUID_REGEX = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

const DEFAULT_LIMIT = 20;
const MAX_LIMIT = 50;
// Same reason as in routes/messages.ts: an unbounded offset makes PostgreSQL scan
// and discard that many rows.
const MAX_OFFSET = 10_000;

// ─────────────────────────────────────────────
// Helper: pagination parameters
// ─────────────────────────────────────────────
// Lenient like GET /conversations/:id/messages: an absent or unreadable value falls
// back to the default instead of answering 400.
// Express gives an array for `?limit=1&limit=2` and an object for `?limit[a]=1`:
// only a plain string is read, anything else counts as absent.
const toInt = (value: unknown): number => (typeof value === 'string' ? parseInt(value, 10) : NaN);

const parsePagination = (query: Request['query']): { offset: number; limit: number } => {
  const offset = Math.min(MAX_OFFSET, Math.max(0, toInt(query.offset) || 0));
  const limit = Math.min(MAX_LIMIT, Math.max(1, toInt(query.limit) || DEFAULT_LIMIT));
  return { offset, limit };
};

// ─────────────────────────────────────────────
// GET /articles?level=easy&offset=0&limit=20
// ─────────────────────────────────────────────
router.get('/', async (req: Request, res: Response) => {
  const { level } = req.query;

  // Strict, unlike the pagination: silently ignoring an unknown level would return
  // ALL articles, and the app would show intermediate texts under an "easy" filter.
  if (level !== undefined && !(ARTICLE_LEVELS as readonly unknown[]).includes(level)) {
    res.status(400).json({ error: `level must be one of: ${ARTICLE_LEVELS.join(', ')}` });
    return;
  }

  try {
    const { offset, limit } = parsePagination(req.query);
    const articles = await listArticles(level as ArticleLevel | undefined, offset, limit);

    res.json({
      articles,
      pagination: { offset, limit, count: articles.length },
    });
  } catch (error) {
    handleError(res, error, 'GET /articles');
  }
});

// ─────────────────────────────────────────────
// GET /articles/:id
// ─────────────────────────────────────────────
router.get('/:id', async (req: Request, res: Response) => {
  if (!UUID_REGEX.test(req.params.id)) {
    res.status(400).json({ error: 'id must be a UUID' });
    return;
  }

  try {
    const article = await getArticle(req.params.id);
    res.json(article);
  } catch (error) {
    handleError(res, error, 'GET /articles/:id');
  }
});

// ─────────────────────────────────────────────
// GET /articles/:id/audio
// ─────────────────────────────────────────────
// Sends the whole file in one response. No Range support on purpose: the app
// downloads the file with its JWT (an <audio> element cannot send the Authorization
// header on web), then plays and seeks in its local copy.
router.get('/:id/audio', async (req: Request, res: Response) => {
  if (!UUID_REGEX.test(req.params.id)) {
    res.status(400).json({ error: 'id must be a UUID' });
    return;
  }

  try {
    const audio = await getArticleAudio(req.params.id);

    res.set({
      // Stored by the ingestion after a strict check (audio/<subtype> only).
      'Content-Type': audio.mimeType,
      'Content-Length': String(audio.size),
      // `private`: the response depends on the Authorization header, a shared cache
      // (CDN, proxy) must not serve it to someone else. One day: an article's audio
      // never changes once stored.
      'Cache-Control': 'private, max-age=86400',
      // These bytes come from a third party: forbid the browser from guessing
      // another type than the one declared.
      'X-Content-Type-Options': 'nosniff',
    });
    // end(), not send(): send() would recompute headers (ETag over megabytes).
    res.status(200).end(audio.data);
  } catch (error) {
    handleError(res, error, 'GET /articles/:id/audio');
  }
});

export default router;
