// Quiz service.
//
// Business logic for quiz results and user statistics:
//   - createQuizSession: stores one finished quiz (session + one row per answer),
//     idempotent and rate limited
//   - getQuizStats: aggregated statistics of one user
//   - getWordProgress: how well one user knows each word, per translation direction
//
// Important context: the vocabulary lives inside the mobile app, so the backend
// CANNOT check that an answer was really correct. It trusts the client. This is
// acceptable because a user can only falsify their own statistics: the user id
// always comes from the JWT, never from the request body.

import { Prisma } from '@prisma/client';
import { prisma } from '../lib/prisma';

// ─────────────────────────────────────────────
// Allowed values and limits
// ─────────────────────────────────────────────
// These lists mirror the types of the mobile app (vocabio2, types/index.ts).
// They are plain strings in the database (see prisma/schema.prisma for why not
// enums), so this is the only place where an unknown value gets rejected.
//
// Pitfall: a new mode, category or level in the app requires this backend to be
// deployed FIRST. Otherwise the route answers 400 and the quiz result is lost.
//
// `as const` turns each array into a tuple of literal types, which lets us derive
// the union types below instead of writing the same values twice.
export const QUIZ_MODES = ['fr-es', 'es-fr'] as const;
export const QUIZ_CATEGORIES = [
  'noun',
  'verb',
  'adjective',
  'adverb',
  'expression',
  'pronoun',
] as const;
export const QUIZ_LEVELS = ['A1', 'A2', 'B1', 'B2', 'C1'] as const;

export type QuizMode = (typeof QUIZ_MODES)[number];
export type QuizCategory = (typeof QUIZ_CATEGORIES)[number];
export type QuizLevel = (typeof QUIZ_LEVELS)[number];

// A quiz has 10 questions today. 50 leaves room for longer quizzes while still
// bounding the size of one insert.
export const MAX_ANSWERS_PER_SESSION = 50;
// Number of words returned in "mostMissedWords".
export const MOST_MISSED_LIMIT = 10;
// Rate limit: a user cannot create more than one session in this time window.
export const MIN_SECONDS_BETWEEN_SESSIONS = 10;

export interface QuizAnswerInput {
  wordId: string;
  category: QuizCategory;
  level: QuizLevel;
  isCorrect: boolean;
}

// Same error convention as assertParticipant (conversationService.ts): a plain
// Error carrying a `statusCode`, which handleError() turns into the HTTP status.
const httpError = (statusCode: number, message: string): Error => {
  const err = new Error(message);
  (err as any).statusCode = statusCode;
  return err;
};

// Fields returned to the client for a session. `userId` is selected as well, but
// only to check the owner: it is removed before returning (see resolveExisting).
const SESSION_SELECT = {
  id: true,
  userId: true,
  mode: true,
  score: true,
  total: true,
  createdAt: true,
} as const;

// ─────────────────────────────────────────────
// resolveExisting (security guard)
// ─────────────────────────────────────────────
/**
 * Looks up a session by id and makes sure the caller owns it.
 *
 * This is the ONLY place where an existing session is read, on purpose: every
 * path that could return a stored session (replay, race on insert) goes through
 * this owner check, so a session can never be returned to another user.
 *
 * @returns null if the id is free, the session if it belongs to `userId`
 * @throws 409 if the id is already used by another user (generic message, no data)
 */
const resolveExisting = async (sessionId: string, userId: string) => {
  const existing = await prisma.quizSession.findUnique({
    where: { id: sessionId },
    select: SESSION_SELECT,
  });

  if (!existing) {
    return null;
  }

  if (existing.userId !== userId) {
    // 409 Conflict rather than 403/404: from the client's point of view the id it
    // generated is simply not usable. The message reveals nothing about the session.
    throw httpError(409, 'This quiz session id is already in use');
  }

  // Drop userId from what we hand back (the client already knows who it is).
  const { userId: _owner, ...session } = existing;
  return session;
};

// ─────────────────────────────────────────────
// createQuizSession
// ─────────────────────────────────────────────
/**
 * Stores a finished quiz: one QuizSession row and one QuizAnswer row per question.
 *
 * Idempotent: `sessionId` is generated by the client. Sending the same quiz twice
 * stores it once; the second call returns the stored session with `created: false`.
 *
 * @param userId - Authenticated user (from the JWT)
 * @param sessionId - UUID generated by the client, used as idempotency key
 * @param mode - Translation direction of the quiz
 * @param answers - One entry per question, in the order they were asked
 * @returns the session and whether it was created by this call
 */
export const createQuizSession = async (
  userId: string,
  sessionId: string,
  mode: QuizMode,
  answers: QuizAnswerInput[]
) => {
  // Step 1: replay? If this user already stored this session, return it as is.
  const existing = await resolveExisting(sessionId, userId);
  if (existing) {
    return { session: existing, created: false };
  }

  // Step 2: rate limit. Done AFTER the replay check on purpose: retrying the same
  // quiz must stay a success, only a NEW session can be refused.
  //
  // Why in the database rather than an in-memory limiter (express-rate-limit)?
  // No new dependency, it survives a restart, and it stays correct if the app
  // ever runs on several instances. The query is served by @@index([userId, createdAt]).
  //
  // Known limit: "check then create" is not atomic. Two requests with DIFFERENT ids
  // sent at the same instant can both pass. Accepted: the goal is to stop a loop
  // from filling the table, not to be exact.
  const latest = await prisma.quizSession.findFirst({
    where: { userId },
    orderBy: { createdAt: 'desc' },
    select: { id: true, createdAt: true },
  });

  // Pitfall: the latest session can be the very one we were asked to create. It
  // happens when the app sends the same quiz twice at the same instant: the other
  // request stored it between our step 1 (which saw nothing) and this query.
  // Without this check we would answer 429 for a quiz that IS stored, and the app
  // would report a failure. It is a replay, so we answer like one. Nothing is
  // written here: the session already exists, we only read it back.
  if (latest?.id === sessionId) {
    const raced = await resolveExisting(sessionId, userId);
    if (raced) {
      return { session: raced, created: false };
    }
  }

  if (latest) {
    const elapsedMs = Date.now() - latest.createdAt.getTime();
    if (elapsedMs < MIN_SECONDS_BETWEEN_SESSIONS * 1000) {
      throw httpError(
        429,
        `Too many quiz sessions: wait ${MIN_SECONDS_BETWEEN_SESSIONS} seconds between two quizzes`
      );
    }
  }

  // Step 3: compute score and total here. The client never sends them, so they can
  // never disagree with the answers.
  const score = answers.filter((answer) => answer.isCorrect).length;
  const total = answers.length;

  try {
    // Step 4: one nested create = one transaction. Either the session and all its
    // answers are stored, or nothing is: no session without its answers.
    const created = await prisma.quizSession.create({
      data: {
        id: sessionId,
        userId,
        mode,
        score,
        total,
        answers: {
          create: answers.map((answer, position) => ({
            position, // index in the array = order of the question in the quiz
            wordId: answer.wordId,
            category: answer.category,
            level: answer.level,
            isCorrect: answer.isCorrect,
          })),
        },
      },
      select: SESSION_SELECT,
    });

    const { userId: _owner, ...session } = created;
    return { session, created: true };
  } catch (error) {
    // Step 5: P2002 = unique constraint violation. It happens when two identical
    // requests race: both passed step 1, one insert won, this one lost on the
    // primary key. The session exists now, so we treat it as a replay.
    // We go through resolveExisting again so the owner check also applies here.
    if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === 'P2002') {
      const raced = await resolveExisting(sessionId, userId);
      if (raced) {
        return { session: raced, created: false };
      }
    }
    throw error;
  }
};

// ─────────────────────────────────────────────
// getQuizStats
// ─────────────────────────────────────────────

// Ratio rounded to 3 decimals, or null when there is nothing to divide by
// (a user with no quiz has no accuracy, which is different from 0 %).
const toAccuracy = (correct: number, answers: number): number | null =>
  answers === 0 ? null : Math.round((correct / answers) * 1000) / 1000;

/**
 * Turns rows grouped by (key, isCorrect) into one entry per key.
 *
 * The database returns up to two rows per key, e.g. for categories:
 *   { category: 'noun', isCorrect: true,  count: 33 }
 *   { category: 'noun', isCorrect: false, count: 7 }
 * and we want: { key: 'noun', answers: 40, correct: 33, accuracy: 0.825 }.
 *
 * `order` gives a stable, meaningful output order (A1 before A2, not alphabetical
 * luck). A value missing from `order` is not expected, but is kept at the end
 * rather than silently dropped.
 */
const foldByKey = (
  rows: { key: string; isCorrect: boolean; count: number }[],
  order: readonly string[]
) => {
  const totals = new Map<string, { answers: number; correct: number }>();
  for (const row of rows) {
    const entry = totals.get(row.key) ?? { answers: 0, correct: 0 };
    entry.answers += row.count;
    if (row.isCorrect) {
      entry.correct += row.count;
    }
    totals.set(row.key, entry);
  }

  const rank = (key: string) => {
    const index = order.indexOf(key);
    return index === -1 ? order.length : index;
  };

  return [...totals.entries()]
    .sort(([a], [b]) => rank(a) - rank(b) || a.localeCompare(b))
    .map(([key, { answers, correct }]) => ({
      key,
      answers,
      correct,
      accuracy: toAccuracy(correct, answers),
    }));
};

/**
 * Aggregated quiz statistics of one user.
 *
 * Four GROUP BY queries run in parallel, then the result is shaped in memory.
 * Every query is filtered by `userId`: sessions directly, answers through their
 * session (`session: { userId }`), because QuizAnswer has no userId column.
 *
 * The response only contains `wordId` for missed words: the app owns the
 * vocabulary and resolves the id to the actual word.
 *
 * @param userId - Authenticated user (from the JWT)
 */
export const getQuizStats = async (userId: string) => {
  const [sessionsByMode, answersByCategory, answersByLevel, missedWords] = await Promise.all([
    // score and total are stored on the session, so these totals need no join.
    prisma.quizSession.groupBy({
      by: ['mode'],
      where: { userId },
      _count: { _all: true },
      _sum: { score: true, total: true },
      _max: { createdAt: true },
    }),
    prisma.quizAnswer.groupBy({
      by: ['category', 'isCorrect'],
      where: { session: { userId } },
      _count: { _all: true },
    }),
    prisma.quizAnswer.groupBy({
      by: ['level', 'isCorrect'],
      where: { session: { userId } },
      _count: { _all: true },
    }),
    // Words answered wrong most often. Secondary sort on wordId: without it, words
    // with the same count could come back in a different order on each call.
    prisma.quizAnswer.groupBy({
      by: ['wordId'],
      where: { session: { userId }, isCorrect: false },
      _count: { wordId: true },
      orderBy: [{ _count: { wordId: 'desc' } }, { wordId: 'asc' }],
      take: MOST_MISSED_LIMIT,
    }),
  ]);

  const byMode = sessionsByMode
    .map((row) => {
      // _sum is null when the group is empty; cannot happen for an existing group,
      // but the generated type says "number | null", hence the fallback.
      const answers = row._sum.total ?? 0;
      const correct = row._sum.score ?? 0;
      return {
        mode: row.mode,
        sessions: row._count._all,
        answers,
        correct,
        accuracy: toAccuracy(correct, answers),
      };
    })
    .sort(
      (a, b) =>
        QUIZ_MODES.indexOf(a.mode as QuizMode) - QUIZ_MODES.indexOf(b.mode as QuizMode)
    );

  const totalSessions = byMode.reduce((sum, row) => sum + row.sessions, 0);
  const totalAnswers = byMode.reduce((sum, row) => sum + row.answers, 0);
  const totalCorrect = byMode.reduce((sum, row) => sum + row.correct, 0);

  // Most recent session over all modes = the latest of the per-mode maximums.
  const lastSessionAt = sessionsByMode.reduce<Date | null>((latest, row) => {
    const candidate = row._max.createdAt;
    if (candidate && (!latest || candidate > latest)) {
      return candidate;
    }
    return latest;
  }, null);

  const byCategory = foldByKey(
    answersByCategory.map((row) => ({
      key: row.category,
      isCorrect: row.isCorrect,
      count: row._count._all,
    })),
    QUIZ_CATEGORIES
  ).map(({ key, ...rest }) => ({ category: key, ...rest }));

  const byLevel = foldByKey(
    answersByLevel.map((row) => ({
      key: row.level,
      isCorrect: row.isCorrect,
      count: row._count._all,
    })),
    QUIZ_LEVELS
  ).map(({ key, ...rest }) => ({ level: key, ...rest }));

  return {
    totalSessions,
    totalAnswers,
    totalCorrect,
    accuracy: toAccuracy(totalCorrect, totalAnswers),
    lastSessionAt,
    byMode,
    byCategory,
    byLevel,
    mostMissedWords: missedWords.map((row) => ({
      wordId: row.wordId,
      wrong: row._count.wordId,
    })),
  };
};

// ─────────────────────────────────────────────
// getWordProgress
// ─────────────────────────────────────────────
/**
 * Progress of one user on each word, per translation direction: one entry per
 * (wordId, mode) the user has answered at least once.
 *
 * Nothing is stored for this: it is COMPUTED from the answers of the finished
 * quizzes (QuizAnswer), the only thing the app ever sends. Consequences:
 *   - no extra table, no extra write: POST /quiz-sessions stays the single write path;
 *   - a quiz closed midway is never sent, so it never counts here;
 *   - the progress can never disagree with the statistics, both read the same rows.
 *
 * Why in JavaScript rather than a GROUP BY: totalSeen / totalCorrect would fit a
 * groupBy, but correctStreak depends on the ORDER of the answers (it restarts at 0 on
 * a wrong answer), which a plain aggregate cannot express. So the answers are read
 * oldest first and folded once.
 *
 * Known limit: this reads every answer of the user on each call (10 rows per quiz).
 * Fine at today's scale; if it ever gets slow, store the counters in a table updated
 * by createQuizSession.
 *
 * The mastery level shown in the app ('new' / 'seen' / 'mastered') is not returned:
 * the app derives it from correctStreak and totalSeen, so the threshold lives there only.
 *
 * @param userId - Authenticated user (from the JWT)
 */
export const getWordProgress = async (userId: string) => {
  const answers = await prisma.quizAnswer.findMany({
    where: { session: { userId } },
    select: {
      wordId: true,
      isCorrect: true,
      session: { select: { mode: true, createdAt: true } },
    },
    // Oldest first, then the order of the questions inside a quiz. sessionId breaks
    // the tie between two sessions created at the same millisecond, so their answers
    // are never interleaved.
    orderBy: [{ session: { createdAt: 'asc' } }, { sessionId: 'asc' }, { position: 'asc' }],
  });

  const progress = new Map<
    string,
    {
      wordId: string;
      mode: string;
      correctStreak: number;
      totalSeen: number;
      totalCorrect: number;
      lastSeenAt: Date;
    }
  >();

  for (const answer of answers) {
    const { mode, createdAt } = answer.session;
    // '|' cannot appear in a mode, so two different (wordId, mode) pairs never collide.
    const key = `${mode}|${answer.wordId}`;
    const entry = progress.get(key) ?? {
      wordId: answer.wordId,
      mode,
      correctStreak: 0,
      totalSeen: 0,
      totalCorrect: 0,
      lastSeenAt: createdAt,
    };

    entry.totalSeen += 1;
    if (answer.isCorrect) {
      entry.totalCorrect += 1;
      entry.correctStreak += 1;
    } else {
      // A wrong answer breaks the streak, whatever came before.
      entry.correctStreak = 0;
    }
    // Answers come oldest first, so the last one seen is the most recent.
    entry.lastSeenAt = createdAt;

    progress.set(key, entry);
  }

  return [...progress.values()];
};
